import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Providers";
import Navbar from "./components/Header/Navbar";
import MobileNavbar from "./components/Header/MobileNavbar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Navbar />
          <MobileNavbar />
        </header>

        <main className="min-h-screen">
          <AuthProvider>{children}</AuthProvider>
          <Toaster />
        </main>
      </body>
    </html>
  );
}
